"""Drop shadows for the ver3 sprites, generated from the images under ver3/asset and kept beside them.

A shadow is the sprite's silhouette above its pivot (the feet), laid flat on the ground and sheared
down-right, away from the light at the screen's upper left. The silhouette is grown by GROW px and
filled with CORE alpha, inside a blurred halo of up to HALO alpha. Shadow images are black with the
shadow in alpha; the game picks the color.

refresh() keeps asset/shadows.yaml and the shadow images in step with their sources: an entry is
rebuilt when its source image, its frame geometry or this file changes. build_assets.py calls it
after packing the sprites, and the loader calls it on start-up. Rebuilding needs Pillow.
"""
import hashlib
import json
import math
from pathlib import Path

import yaml

SLOPE = (.6, .3)   # ground travel per pixel of height: right, down (2:1, along the map grid)
GROW = 1           # px added around the silhouette
CORE, HALO = 130, 110
BLUR = 3           # box blur radius, applied twice
PAD = GROW + 2*BLUR + 1
CASTERS = ('rock_', 'tree_')  # tileset animations whose frames cast shadows
INDEX = 'shadows.yaml'
HEADER = """\
# Drop shadows, generated by ver3/shadows.py from the images named in `source`. Do not edit:
# an entry is rebuilt when its source, its frame geometry or shadows.py changes (see `hash`).
#
# Images are black, the shadow is in alpha. Draw a shadow so that its pivot lands on the
# sprite's pivot, onto one shadow layer below all sprites.
# units.<key>: same rows and columns as the unit image, cells of `cell` with `pivot`.
# tileset.sprites[tileset sprite id] = [x, y, w, h, pivot_x, pivot_y].
"""


def shadow(sprite, pivot):
    """Shadow image of one RGBA sprite and the sprite's pivot inside it."""
    from PIL import Image, ImageChops, ImageFilter
    a, b = SLOPE
    w = sprite.width
    px, py = pivot
    silhouette = sprite.getchannel('A').point(lambda v: 255 if v else 0)
    depth = math.ceil(py*b)
    flat = Image.new('L', (w + math.ceil(py*a) + 2*PAD, depth + 1 + 2*PAD))
    for d in range(depth + 1):
        src = round(py - d/b)
        if src < 0:
            break
        x, y = PAD + round(d/b*a), PAD + d
        flat.paste(255, (x, y, x + w, y + 1), mask=silhouette.crop((0, src, w, src + 1)))
    grown = flat.filter(ImageFilter.MaxFilter(2*GROW + 1)) if GROW else flat
    halo = grown.filter(ImageFilter.BoxBlur(BLUR)).filter(ImageFilter.BoxBlur(BLUR))
    alpha = ImageChops.lighter(grown.point(lambda v: CORE if v else 0), halo.point(lambda v: v*HALO//255))
    black = Image.new('L', alpha.size)
    return Image.merge('RGBA', (black, black, black, alpha)), (px + PAD, PAD)


def unit_sheet(image, cell, pivot):
    """Shadow sheet with the same rows and columns as a unit image."""
    from PIL import Image
    w, h = cell
    cols, rows = image.width//w, image.height//h
    sheet = None
    for row in range(rows):
        for col in range(cols):
            cast, spivot = shadow(image.crop((col*w, row*h, (col + 1)*w, (row + 1)*h)), pivot)
            if sheet is None:
                sheet = Image.new('RGBA', (cast.width*cols, cast.height*rows))
            sheet.paste(cast, (col*cast.width, row*cast.height))
    return sheet, list(cast.size), list(spivot)


def tileset_strip(image, sprites):
    """Shadows of the given tileset sprites side by side; returns the strip and their rects."""
    from PIL import Image
    casts, x = {}, 0
    for sid, (sx, sy, w, h, px, py) in sprites.items():
        cast, (cx, cy) = shadow(image.crop((sx, sy, sx + w, sy + h)), (px, py))
        casts[sid] = (cast, [x, 0, cast.width, cast.height, cx, cy])
        x += cast.width
    strip = Image.new('RGBA', (x, max(c.height for c, _ in casts.values())))
    for cast, rect in casts.values():
        strip.paste(cast, (rect[0], 0))
    return strip, {sid: rect for sid, (_, rect) in casts.items()}


def digest(*parts):
    h = hashlib.sha1(Path(__file__).read_bytes())
    for part in parts:
        h.update(part if isinstance(part, bytes) else json.dumps(part, sort_keys=True).encode())
    return h.hexdigest()[:16]


def refresh(index, asset_dir):
    """Rebuild stale shadows for the sprites in assets.yaml `index`; returns the shadow index."""
    from PIL import Image
    path = asset_dir/INDEX
    old = yaml.safe_load(path.read_text()) if path.exists() else {}
    units = {}
    for key, spec in index['units'].items():
        source = spec['image']
        stamp = digest((asset_dir/source).read_bytes(), spec['cell'], spec['pivot'])
        entry = (old.get('units') or {}).get(key)
        if not entry or entry['hash'] != stamp or not (asset_dir/entry['image']).exists():
            sheet, cell, pivot = unit_sheet(Image.open(asset_dir/source).convert('RGBA'), spec['cell'], spec['pivot'])
            entry = dict(image=f'units/{key}.shadow.png', source=source, hash=stamp, cell=cell, pivot=pivot)
            sheet.save(asset_dir/entry['image'])
            print('shadow', entry['image'])
        units[key] = entry
    tiles = index['tileset']
    ids = sorted({f for name, a in tiles['animations'].items() if name.startswith(CASTERS) for f in a['frames']})
    sprites = {sid: tiles['sprites'][sid] for sid in ids}
    stamp = digest((asset_dir/tiles['image']).read_bytes(), sprites)
    tileset = old.get('tileset')
    if not tileset or tileset['hash'] != stamp or not (asset_dir/tileset['image']).exists():
        strip, rects = tileset_strip(Image.open(asset_dir/tiles['image']).convert('RGBA'), sprites)
        tileset = dict(image='map/shadows.png', source=tiles['image'], hash=stamp, sprites=rects)
        strip.save(asset_dir/tileset['image'])
        print('shadow', tileset['image'])
    new = dict(units=units, tileset=tileset)
    if new != old:
        path.write_text(HEADER + yaml.safe_dump(new, sort_keys=False, default_flow_style=None, width=140))
    return new
